### ISSUE TITLE
User being sent back to home screen on Nexus

### ISSUE THREAD

**Issue by ivanperez-keera** [keera-studios/magic-cookies#1]
A Nexus 5 user has reported he is being sent back to the home screen.

https://twitter.com/mwjacks0n/status/578584932039155713

**Comment by ivanperez-keera** [comment]
A nexus 7 user reported the same thing "around level 7". (Private conversation.)

**Comment by bsummer4** [comment]
I'm using an Nexut 5, and I also get intermittent crashes during level 5.

**Comment by ivanperez-keera** [comment]
A new version (1.26) should be available right now. Could you try and see if it works better?

**Comment by ivanperez-keera** [comment]
I got access to a nexus today and I was able to reproduce the error. I can't post the logcat (not my phone -- it may include private info), but there was enough to guess what may be going on.

**Comment by ivanperez-keera** [comment]
Sorry that it took so long.

This is just to let you know that we've been looking into this bug and we've been able to replicate it on a Nexus phone.

We are now rolling out version 1.28 to beta testers, to see if it solves the issue. If it works as expected, it should be on the market in one or two days.

**Comment by bsummer4** [comment]
Ok, great. Thanks!

**Comment by ivanperez-keera** [comment]
An update was pushed earlier today. Please, give it a try.

I cannot claim that it will fix all the problems, but I tried it on a nexus for hours and it seemed to work.

If it fails, and if you have a chance to send a logcat, it would be of great help.

I'll leave the bug open for a while.

**Comment by ivanperez-keera** [comment]
Fixed in 1.32.
